# Generated by Django 5.2.4 on 2025-07-29 22:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0003_remove_paciente_email'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='fecha_nacimiento',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='paciente',
            name='numero_documento',
            field=models.CharField(max_length=10, null=True, unique=True),
        ),
    ]
