# Generated by Django 5.2.4 on 2025-07-30 20:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0005_alter_paciente_numero_documento_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='celular',
            field=models.CharField(max_length=13),
        ),
    ]
