# Generated by Django 5.2.4 on 2025-07-30 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('negocio', '0006_alter_paciente_celular'),
    ]

    operations = [
        migrations.AlterField(
            model_name='paciente',
            name='celular',
            field=models.CharField(max_length=20),
        ),
    ]
